//--------------------------------------------------------
//Code generated by Papyrus Java
//--------------------------------------------------------

package main.java.softdesign;

/************************************************************/
/**
* 
*/
public class Color {
	/**
	 * 
	 */
	private int red;
	/**
	 * 
	 */
	private int green;
	/**
	 * 
	 */
	public int blue;
	/**
	 * 
	 * @param red 
	 * @param green 
	 * @param blue 
	 */
	public Color(int red, int green, int blue) {
		this.red = red;
		this.green = green;
		this.blue = blue;
	}
	/**
	 * @return
	 * 
	 * Detects color given and returns corresponding color name as string
	 */
	public String detectColor(){
		if (red > 250 && green < 50 && blue < 50)
			return "Red";
		else if (red < 50 && green > 250 && blue < 50)
			return "Green";
		else if (red < 50 && green < 50 && blue > 250)
			return "Blue";
		else if (red > 200 && green > 200 && blue < 50)
			return "Yellow";
		else if (red < 50 && green > 200 && blue > 200)
			return "Cyan";
		else if (red > 200 && green < 50 && blue > 200)
			return "Magenta";
		else if (red < 50 && green < 50 && blue < 50)
			return "Black";
		else
			return "Unknown Color";
	}
};
