//--------------------------------------------------------
//Code generated by Papyrus Java
//--------------------------------------------------------

package main.java.softdesign;

/************************************************************/
/**
* 
*/
public class Color {
	/**
	 * 
	 */
	public static int red;
	/**
	 * 
	 */
	public static int green;
	/**
	 * 
	 */
	public static int blue;

	/**
	 * 
	 * @param red 
	 * @param green 
	 * @param blue 
	 */
	public Color(int red, int green, int blue) {
	}
};
