//--------------------------------------------------------
//Code generated by Papyrus Java
//--------------------------------------------------------

package main.java.softdesign;

/************************************************************/
/**
* 
*/
public class Color {
	/**
	 * 
	 */
	public int red;
	/**
	 * 
	 */
	public int green;
	/**
	 * 
	 */
	public int blue;
	
	public String detect_color(){
		if (red > 250 && green < 50 && blue < 50)
			return "red";
		else if (red < 50 && green > 250 && blue < 50)
			return "green";
		else if (red < 50 && green < 50 && blue > 250)
			return "blue";
		else if (red > 200 && green > 200 && blue < 50)
			return "yellow";
		else if (red < 50 && green > 200 && blue > 200)
			return "cyan";
		else if (red > 200 && green < 50 && blue > 200)
			return "magenta";
		else if (red < 50 && green < 50 && blue < 50)
			return "black";
		else
			return "fail";
	}

	/**
	 * 
	 * @param red 
	 * @param green 
	 * @param blue 
	 */
	public Color(int red, int green, int blue) {
		this.red = red;
		this.green = green;
		this.blue = blue;
	}
};
