//--------------------------------------------------------
//Code generated by Papyrus Java
//--------------------------------------------------------

package main.java.softdesign;

/************************************************************/
/**
* 
*/
public class Coordinates {
	/**
	 * 
	 */
	public double x;
	/**
	 * 
	 */
	public double y;

	/**
	 * 
	 * @param x 
	 * @param y 
	 */
	public Coordinates(double x, double y) {
		this.x = x;
		this.y = y;
	}
	public Coordinates(Coordinates copy) {
		this.x = copy.x;
		this.y = copy.y;
	}
};
