//--------------------------------------------------------
//Code generated by Papyrus Java
//--------------------------------------------------------

package main.java.softdesign;

/************************************************************/
/**
* 
*/
public class Coordinates {
	/**
	 * 
	 */
	public static double x;
	/**
	 * 
	 */
	public static double y;

	/**
	 * 
	 * @param x 
	 * @param y 
	 */
	public Coordinates(double x, double y) {
		Coordinates.x = x;
		Coordinates.y = y;
	}
};
