//--------------------------------------------------------
//Code generated by Papyrus Java
//--------------------------------------------------------


package main.java.softdesign;

import java.util.ArrayList;

/************************************************************/
/**
* 
*/
public class Object {
	/**
	 * 
	 */
	private ArrayList<Coordinates> coordinatesArray = new ArrayList<Coordinates>();
	
	
	private Color color;

	/**
	 * 
	 * @param obstacle_coords 
	 * @param color 
	 */
	public void addCoordinates(Coordinates coordinates) {
		coordinatesArray.add(coordinates);
	}
	
	public void setColor(Color color) {
		this.color = color;
	}
	
	public Color getColor() {
		return color;
	}
};
