//--------------------------------------------------------
//Code generated by Papyrus Java
//--------------------------------------------------------


package main.java.softdesign;

/************************************************************/
/**
* 
*/
public class Object {
	/**
	 * 
	 */
	public Coordinates[] coordinates_array = new Coordinates[10000];

	/**
	 * 
	 * @param obstacle_coords 
	 * @param color 
	 */
	public Object(Coordinates obstacle_coords, Color color) {
		this.coordinates_array[0] = obstacle_coords;
	}
};
